language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
env:
  - BUILD=false    TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../compat/lodash.js&loader=curl"
  - BUILD=false    TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../compat/lodash.js&loader=dojo"
  - BUILD=false    TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../compat/lodash.js&loader=requirejs"
  - BUILD=false    TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../modern/lodash.js&loader=curl"
  - BUILD=false    TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../modern/lodash.js&loader=dojo"
  - BUILD=false    TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../modern/lodash.js&loader=requirejs"
  - BUILD="legacy" TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../$BUILD/lodash.js&loader=curl"
  - BUILD="legacy" TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../$BUILD/lodash.js&loader=dojo"
  - BUILD="legacy" TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../$BUILD/lodash.js&loader=requirejs"
  - BUILD="mobile" TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../$BUILD/lodash.js&loader=curl"
  - BUILD="mobile" TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../$BUILD/lodash.js&loader=dojo"
  - BUILD="mobile" TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../$BUILD/lodash.js&loader=requirejs"
git:
  depth: 1
branches:
  only:
    - master
script:
  - "git clone --depth=1 --branch=master git://github.com/lodash/lodash.git ./node_modules/lodash"
  - "[ $BUILD != false ] && git clone --depth=1 --branch=master git://github.com/lodash/lodash-cli.git ./node_modules/lodash-cli || true"
  - "[ $BUILD != false ] && mkdir ./node_modules/lodash-cli/node_modules && cd ./node_modules/lodash-cli/node_modules/ && ln -s ../../lodash ./lodash && cd ../../../ || true"
  - "[ $BUILD != false ] && node ./node_modules/lodash-cli/bin/lodash modularize exports=amd -o ./$BUILD || true"
  - $TEST_COMMAND
