language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
env:
  - BUILD=false TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../compat/lodash.js&loader=curl"
  - BUILD=false TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../compat/lodash.js&loader=dojo"
  - BUILD=false TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../compat/lodash.js&loader=requirejs"
  - BUILD=false TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../modern/lodash.js&loader=curl"
  - BUILD=false TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../modern/lodash.js&loader=dojo"
  - BUILD=false TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../modern/lodash.js&loader=requirejs"
  - BUILD=true  TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../legacy/lodash.js&loader=curl"
  - BUILD=true  TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../legacy/lodash.js&loader=dojo"
  - BUILD=true  TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../legacy/lodash.js&loader=requirejs"
  - BUILD=true  TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../mobile/lodash.js&loader=curl"
  - BUILD=true  TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../mobile/lodash.js&loader=dojo"
  - BUILD=true  TEST_COMMAND="phantomjs ./node_modules/lodash/test/test.js node_modules/lodash/test/index.html?modularize&build=../../../mobile/lodash.js&loader=requirejs"
git:
  depth: 1
branches:
  only:
    - master
script:
  - "git clone --depth=1 --branch=master git://github.com/lodash/lodash.git ./node_modules/lodash"
  - "$BUILD && git clone --depth=1 --branch=master git://github.com/lodash/lodash-cli.git ./node_modules/lodash-cli"
  - "$BUILD && mkdir ./node_modules/lodash-cli/node_modules && cd ./node_modules/lodash-cli/node_modules/ && ln -s ../../lodash ./lodash && cd ../../../"
  - "$BUILD && node ./node_modules/lodash-cli/bin/lodash modularize exports=amd -o ./legacy"
  - "$BUILD && node ./node_modules/lodash-cli/bin/lodash modularize exports=amd -o ./mobile"
  - $TEST_COMMAND
