language: node_js
node_js:
  - "0.10"
env:
  global:
    - BIN="phantomjs" BUILD="compat" ISTANBUL=false SAUCE_LABS=false SAUCE_USERNAME="lodash"
    - secure: "X3/H+ZNbvxsD/wxQ0uP0d3KpFh2rJFuzqFbz8fG3KK97ZlZv4SYtgQoVzIx+rDClSHPOddTvbry3NusZ2JNadbcQRIaZCgBOE8FBX10YIR1ESDjxFBTZqRj8APD5/4L3akhyOQ62gEWTL4wT8TojIzRoT2bNzXEr6DyupVGW4qk="
  matrix:
    - LOADER="curl"
    - LOADER="dojo"
    - LOADER="requirejs"
    - BUILD="modern" LOADER="curl"
    - BUILD="modern" LOADER="dojo"
    - BUILD="modern" LOADER="requirejs"
matrix:
  include:
    - node_js: "0.10"
      env: ISTANBUL=true   BUILD="modern-coverage" LOADER="requirejs"
    - node_js: "0.10"
      env: SAUCE_LABS=true LOADER="curl"
    - node_js: "0.10"
      env: SAUCE_LABS=true LOADER="dojo"
    - node_js: "0.10"
      env: SAUCE_LABS=true LOADER="requirejs"
    - node_js: "0.10"
      env: SAUCE_LABS=true BUILD="modern" LOADER="curl"
    - node_js: "0.10"
      env: SAUCE_LABS=true BUILD="modern" LOADER="dojo"
    - node_js: "0.10"
      env: SAUCE_LABS=true BUILD="modern" LOADER="requirejs"
    - node_js: "0.10"
      env: SAUCE_LABS=true BUILD="underscore" LOADER="curl"
    - node_js: "0.10"
      env: SAUCE_LABS=true BUILD="underscore" LOADER="dojo"
    - node_js: "0.10"
      env: SAUCE_LABS=true BUILD="underscore" LOADER="requirejs"
git:
  depth: 10
branches:
  only:
    - master
before_install:
  - "git clone --depth=10 --branch=master git://github.com/lodash/lodash.git ./node_modules/lodash"
  - "[ $SAUCE_LABS == false ] || BIN=\"node\""
  - "[ $SAUCE_LABS == false ] || npm i chalk@\"~0.4.0\" ecstatic@\"~0.4.0\" request@\"~2.34.0\" sauce-tunnel-sc3-1@\"~1.0.0\""
  - "[ $ISTANBUL == false ]   || npm i -g coveralls@\"~2.10.0\" istanbul@\"~0.2.0\""
script:
  - "[ $ISTANBUL == false ]    || istanbul instrument --output ./$BUILD ./modern"
  - "[ $SAUCE_LABS == true ]   || phantomjs --disk-cache=true ./node_modules/lodash/test/test.js \"node_modules/lodash/test/index.html?build=../../../$BUILD/main.js&loader=$LOADER&noglobals=true\""
  - "[ $ISTANBUL == false ]    || istanbul report lcovonly"
  - "[ $ISTANBUL == true ] && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage || true"
  - "([ $SAUCE_LABS == false ] || [ $BUILD == 'underscore' ]) || $BIN ./node_modules/lodash/test/saucelabs.js name=\"lodash tests\" runner=\"node_modules/lodash/test/index.html?build=../../../$BUILD/main.js&loader=$LOADER\" tags=\"$BUILD,$LOADER,amd,development\""
  - "([ $SAUCE_LABS == false ] || [ $BUILD != 'compat' ])     || $BIN ./node_modules/lodash/test/saucelabs.js name=\"lodash tests\" runner=\"node_modules/lodash/test/index.html?build=../../../$BUILD/main.js&loader=$LOADER\" tags=\"$BUILD,$LOADER,amd,development,ie-compat\" compatMode=7"
  - "[ $SAUCE_LABS == false ]  || $BIN ./node_modules/lodash/test/saucelabs.js name=\"backbone tests\"   runner=\"node_modules/lodash/test/backbone.html?build=../../../$BUILD/main.js&loader=$LOADER\" tags=\"$BUILD,$LOADER,amd,development,backbone\""
  - "[ $SAUCE_LABS == false ]  || $BIN ./node_modules/lodash/test/saucelabs.js name=\"underscore tests\" runner=\"node_modules/lodash/test/underscore.html?build=../../../$BUILD/main.js&loader=$LOADER\" tags=\"$BUILD,$LOADER,amd,development,underscore\""
