language: node_js
node_js:
  - "0.10"
env:
  global:
    - BUILD="compat" COMPAT=false MAKE=false SAUCE_LABS=false SAUCE_USERNAME="lodash"
    - secure: "b1Id0bcgTs4c31K5SMoH6glrbuxafSPu3mV0pzVf6dMr75FSwtnAhR0hO02YhKdyqHPqq01IfoGOy5x1t6zPY4az1Wkg7yt0qae4ckv1/0KMO8sOahsNQoTxspuBRwj1RSKJwCR/xn41jQJsAVIMezJa1i+iiBXpAVeenl5Yi7U="
  matrix:
    - LOADER="curl"
    - LOADER="dojo"
    - LOADER="requirejs"
    - BUILD="modern" LOADER="curl"
    - BUILD="modern" LOADER="dojo"
    - BUILD="modern" LOADER="requirejs"
    - BUILD="legacy" LOADER="curl"
    - BUILD="legacy" LOADER="dojo"
    - BUILD="legacy" LOADER="requirejs"
    - BUILD="mobile" LOADER="curl"
    - BUILD="mobile" LOADER="dojo"
    - BUILD="mobile" LOADER="requirejs"
matrix:
  include:
    - node_js: "0.8"
      env: SAUCE_LABS=true LOADER="curl"
    - node_js: "0.8"
      env: SAUCE_LABS=true LOADER="dojo"
    - node_js: "0.8"
      env: SAUCE_LABS=true LOADER="requirejs"
    - node_js: "0.8"
      env: SAUCE_LABS=true BUILD="modern" LOADER="curl"
    - node_js: "0.8"
      env: SAUCE_LABS=true BUILD="modern" LOADER="dojo"
    - node_js: "0.8"
      env: SAUCE_LABS=true BUILD="modern" LOADER="requirejs"
    - node_js: "0.8"
      env: SAUCE_LABS=true BUILD="legacy" LOADER="curl"
    - node_js: "0.8"
      env: SAUCE_LABS=true BUILD="legacy" LOADER="dojo"
    - node_js: "0.8"
      env: SAUCE_LABS=true BUILD="legacy" LOADER="requirejs"
    - node_js: "0.8"
      env: SAUCE_LABS=true BUILD="mobile" LOADER="curl"
    - node_js: "0.8"
      env: SAUCE_LABS=true BUILD="mobile" LOADER="dojo"
    - node_js: "0.8"
      env: SAUCE_LABS=true BUILD="mobile" LOADER="requirejs"
    - node_js: "0.8"
      env: SAUCE_LABS=true BUILD="underscore" LOADER="curl"
    - node_js: "0.8"
      env: SAUCE_LABS=true BUILD="underscore" LOADER="dojo"
    - node_js: "0.8"
      env: SAUCE_LABS=true BUILD="underscore" LOADER="requirejs"
git:
  depth: 10
branches:
  only:
    - master
before_install:
  - "git clone --depth=10 --branch=master git://github.com/lodash/lodash.git ./node_modules/lodash"
  - "([ $BUILD == 'legacy' ] || [ $BUILD == 'mobile' ]) && MAKE=true || true"
  - "([ $BUILD == 'compat' ] || [ $BUILD == 'legacy' ]) && COMPAT=true || true"
  - "[ $SAUCE_LABS != false ] && npm i ecstatic@\"~0.4.0\" request@\"~2.27.0\" sauce-tunnel@\"~1.1.0\" || true"
  - "[ $MAKE != false ] && git clone --depth=10 --branch=master git://github.com/lodash/lodash-cli.git ./node_modules/lodash-cli || true"
  - "[ $MAKE != false ] && mkdir ./node_modules/lodash-cli/node_modules && cd ./node_modules/lodash-cli/node_modules/ && ln -s ../../lodash ./lodash && cd ../../../ || true"
  - "[ $MAKE != false ] && node ./node_modules/lodash-cli/bin/lodash modularize $BUILD exports=amd -o ./$BUILD || true"
script:
  - "[ $SAUCE_LABS != false ] && true || phantomjs ./node_modules/lodash/test/test.js \"node_modules/lodash/test/index.html?build=../../../$BUILD/main.js&loader=$LOADER&noglobals=true\""
  - "([ $SAUCE_LABS == false ] || [ $BUILD == 'underscore' ]) && true || node ./node_modules/lodash/test/saucelabs.js runner=\"node_modules/lodash/test/index.html?build=../../../$BUILD/main.js&loader=$LOADER\" tags=\"$BUILD,$LOADER,amd,development\""
  - "([ $SAUCE_LABS == false ] || [ $COMPAT == false ])       && true || node ./node_modules/lodash/test/saucelabs.js runner=\"node_modules/lodash/test/index.html?build=../../../$BUILD/main.js&loader=$LOADER\" tags=\"$BUILD,$LOADER,amd,development,ie-compat\" compatMode=7"
  - "[ $SAUCE_LABS == false ] && true || node ./node_modules/lodash/test/saucelabs.js runner=\"node_modules/lodash/test/underscore.html?build=../../../$BUILD/main.js&loader=$LOADER\" tags=\"$BUILD,$LOADER,amd,development,underscore\""
