language: node_js
node_js:
  - "0.10"
env:
  global:
    - BIN="phantomjs" BUILD="compat" COMPAT=false ISTANBUL=false MAKE=false SAUCE_LABS=false SAUCE_USERNAME="lodash"
    - secure: "X3/H+ZNbvxsD/wxQ0uP0d3KpFh2rJFuzqFbz8fG3KK97ZlZv4SYtgQoVzIx+rDClSHPOddTvbry3NusZ2JNadbcQRIaZCgBOE8FBX10YIR1ESDjxFBTZqRj8APD5/4L3akhyOQ62gEWTL4wT8TojIzRoT2bNzXEr6DyupVGW4qk="
  matrix:
    - LOADER="curl"
    - LOADER="dojo"
    - LOADER="requirejs"
    - BUILD="modern" LOADER="curl"
    - BUILD="modern" LOADER="dojo"
    - BUILD="modern" LOADER="requirejs"
    - BUILD="legacy" LOADER="curl"
    - BUILD="legacy" LOADER="dojo"
    - BUILD="legacy" LOADER="requirejs"
    - BUILD="mobile" LOADER="curl"
    - BUILD="mobile" LOADER="dojo"
    - BUILD="mobile" LOADER="requirejs"
matrix:
  include:
    - node_js: "0.10"
      env: ISTANBUL=true BUILD="modern-coverage" LOADER="requirejs"
    - node_js: "0.10"
      env: SAUCE_LABS=true LOADER="curl"
    - node_js: "0.10"
      env: SAUCE_LABS=true LOADER="dojo"
    - node_js: "0.10"
      env: SAUCE_LABS=true LOADER="requirejs"
    - node_js: "0.10"
      env: SAUCE_LABS=true BUILD="modern" LOADER="curl"
    - node_js: "0.10"
      env: SAUCE_LABS=true BUILD="modern" LOADER="dojo"
    - node_js: "0.10"
      env: SAUCE_LABS=true BUILD="modern" LOADER="requirejs"
    - node_js: "0.10"
      env: SAUCE_LABS=true BUILD="legacy" LOADER="curl"
    - node_js: "0.10"
      env: SAUCE_LABS=true BUILD="legacy" LOADER="dojo"
    - node_js: "0.10"
      env: SAUCE_LABS=true BUILD="legacy" LOADER="requirejs"
    - node_js: "0.10"
      env: SAUCE_LABS=true BUILD="mobile" LOADER="curl"
    - node_js: "0.10"
      env: SAUCE_LABS=true BUILD="mobile" LOADER="dojo"
    - node_js: "0.10"
      env: SAUCE_LABS=true BUILD="mobile" LOADER="requirejs"
    - node_js: "0.10"
      env: SAUCE_LABS=true BUILD="underscore" LOADER="curl"
    - node_js: "0.10"
      env: SAUCE_LABS=true BUILD="underscore" LOADER="dojo"
    - node_js: "0.10"
      env: SAUCE_LABS=true BUILD="underscore" LOADER="requirejs"
git:
  depth: 10
branches:
  only:
    - master
before_install:
  - "git clone --depth=10 --branch=master git://github.com/lodash/lodash.git ./node_modules/lodash"
  - "([ $BUILD == 'legacy' ] || [ $BUILD == 'mobile' ]) && MAKE=true || true"
  - "([ $BUILD == 'compat' ] || [ $BUILD == 'legacy' ]) && COMPAT=true || true"
  - "[ $SAUCE_LABS == false ] || BIN=\"node\""
  - "[ $SAUCE_LABS == false ] || npm i ecstatic@\"~0.4.0\" request@\"~2.27.0\" sauce-tunnel@\"1.1.0\""
  - "[ $ISTANBUL == false ]   || npm i -g coveralls@\"~2.5.0\" istanbul@\"~0.1.0\""
  - "[ $MAKE == false ] || git clone --depth=10 --branch=master git://github.com/lodash/lodash-cli.git ./node_modules/lodash-cli"
  - "[ $MAKE == false ] || (mkdir ./node_modules/lodash-cli/node_modules && cd ./node_modules/lodash-cli/node_modules/ && ln -s ../../lodash ./lodash && cd ../../../)"
  - "[ $MAKE == false ] || node ./node_modules/lodash-cli/bin/lodash modularize $BUILD exports=amd -o ./$BUILD"
script:
  - "[ $ISTANBUL == false ]  || istanbul instrument --output ./$BUILD ./modern"
  - "[ $SAUCE_LABS == true ] || phantomjs ./node_modules/lodash/test/test.js \"node_modules/lodash/test/index.html?build=../../../$BUILD/main.js&loader=$LOADER&noglobals=true\""
  - "[ $ISTANBUL == false ]  || (istanbul report lcovonly && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage)"
  - "([ $SAUCE_LABS == false ] || [ $BUILD == 'underscore' ]) || $BIN ./node_modules/lodash/test/saucelabs.js runner=\"node_modules/lodash/test/index.html?build=../../../$BUILD/main.js&loader=$LOADER\" tags=\"$BUILD,$LOADER,amd,development\""
  - "([ $SAUCE_LABS == false ] || [ $COMPAT == false ])       || $BIN ./node_modules/lodash/test/saucelabs.js runner=\"node_modules/lodash/test/index.html?build=../../../$BUILD/main.js&loader=$LOADER\" tags=\"$BUILD,$LOADER,amd,development,ie-compat\" compatMode=7"
  - "[ $SAUCE_LABS == false ]  || $BIN ./node_modules/lodash/test/saucelabs.js runner=\"node_modules/lodash/test/underscore.html?build=../../../$BUILD/main.js&loader=$LOADER\" tags=\"$BUILD,$LOADER,amd,development,underscore\""
